//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Instruction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Instruction.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Alumno:.
        /// </summary>
        internal static string ALUMNO_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Alumno:.
        /// </summary>
        internal static string ALUMNO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevas Respuestas de Alumno:.
        /// </summary>
        internal static string ALUMNO_EXAMEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_EXAMEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Respuestas de Alumno:.
        /// </summary>
        internal static string ALUMNO_EXAMEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_EXAMEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Alumnos:.
        /// </summary>
        internal static string ALUMNO_FIND_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumnos.
        /// </summary>
        internal static string ALUMNOS {
            get {
                return ResourceManager.GetString("ALUMNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APTO.
        /// </summary>
        internal static string APTO_LABEL {
            get {
                return ResourceManager.GetString("APTO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partes de Asistencia.
        /// </summary>
        internal static string ASISTENCIAS {
            get {
                return ResourceManager.GetString("ASISTENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Caja.
        /// </summary>
        internal static string CAJA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CAJA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la Caja.
        /// </summary>
        internal static string CAJA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("CAJA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Caja.
        /// </summary>
        internal static string CAJA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CAJA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Capacidad:.
        /// </summary>
        internal static string CAPACIDAD_TITLE {
            get {
                return ResourceManager.GetString("CAPACIDAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Clase:.
        /// </summary>
        internal static string CLASE_HORARIO_TITLE {
            get {
                return ResourceManager.GetString("CLASE_HORARIO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Ordenadas:.
        /// </summary>
        internal static string CLASES_ORDENADAS_VIEW_TITLE {
            get {
                return ResourceManager.GetString("CLASES_ORDENADAS_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente:.
        /// </summary>
        internal static string CLIENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Cliente:.
        /// </summary>
        internal static string CLIENTE_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Cliente:.
        /// </summary>
        internal static string CLIENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Clientes:.
        /// </summary>
        internal static string CLIENTE_FIND_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es preciso cerrar sesión antes de configurar el servidor.  ¿Desea continuar?.
        /// </summary>
        internal static string CLOSE_SESSION {
            get {
                return ResourceManager.GetString("CLOSE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicado de Auditoría.
        /// </summary>
        internal static string COMUNICADO_AUDITORIA_TITLE {
            get {
                return ResourceManager.GetString("COMUNICADO_AUDITORIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Servidor:.
        /// </summary>
        internal static string CONFIGURE_SERVER {
            get {
                return ResourceManager.GetString("CONFIGURE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Convocatoria:.
        /// </summary>
        internal static string CONVOCATORIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CONVOCATORIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Convocatoria:.
        /// </summary>
        internal static string CONVOCATORIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CONVOCATORIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cronograma:.
        /// </summary>
        internal static string CRONOGRAMA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CRONOGRAMA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Cronograma: .
        /// </summary>
        internal static string CRONOGRAMA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CRONOGRAMA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronogramas.
        /// </summary>
        internal static string CRONOGRAMAS {
            get {
                return ResourceManager.GetString("CRONOGRAMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Curso:.
        /// </summary>
        internal static string CURSO_ADD_TITLE {
            get {
                return ResourceManager.GetString("CURSO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Curso:.
        /// </summary>
        internal static string CURSO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CURSO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Cursos:.
        /// </summary>
        internal static string CURSO_FIND_TITLE {
            get {
                return ResourceManager.GetString("CURSO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos.
        /// </summary>
        internal static string CURSOS {
            get {
                return ResourceManager.GetString("CURSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Disponibilidad:.
        /// </summary>
        internal static string DISPONIBILIDAD_ADD_TITLE {
            get {
                return ResourceManager.GetString("DISPONIBILIDAD_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Disponibilidad:.
        /// </summary>
        internal static string DISPONIBILIDAD_EDIT_TITLE {
            get {
                return ResourceManager.GetString("DISPONIBILIDAD_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicar Capacidad:.
        /// </summary>
        internal static string DUPLICAR_CAPACIDAD_TITLE {
            get {
                return ResourceManager.GetString("DUPLICAR_CAPACIDAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicar Preguntas:.
        /// </summary>
        internal static string DUPLICAR_PREGUNTAS_TEMA_TITLE {
            get {
                return ResourceManager.GetString("DUPLICAR_PREGUNTAS_TEMA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Empleado:.
        /// </summary>
        internal static string EMPLEADO_ADD_TITLE {
            get {
                return ResourceManager.GetString("EMPLEADO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Empleado:.
        /// </summary>
        internal static string EMPLEADO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("EMPLEADO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Empleados:.
        /// </summary>
        internal static string EMPLEADO_FIND_TITLE {
            get {
                return ResourceManager.GetString("EMPLEADO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string EMPLEADOS {
            get {
                return ResourceManager.GetString("EMPLEADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Examen:.
        /// </summary>
        internal static string EXAMEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("EXAMEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Examen:.
        /// </summary>
        internal static string EXAMEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("EXAMEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Exámenes:.
        /// </summary>
        internal static string EXAMEN_FIND_TITLE {
            get {
                return ResourceManager.GetString("EXAMEN_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes:.
        /// </summary>
        internal static string EXAMENES {
            get {
                return ResourceManager.GetString("EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Extra:.
        /// </summary>
        internal static string EXTRAS_TITLE {
            get {
                return ResourceManager.GetString("EXTRAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALTA ASISTENCIA.
        /// </summary>
        internal static string FALTA_ASISTENCIA_LABEL {
            get {
                return ResourceManager.GetString("FALTA_ASISTENCIA_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Faltas de Alumnos:.
        /// </summary>
        internal static string FALTAS_ALUMNOS_VIEW_TITLE {
            get {
                return ResourceManager.GetString("FALTAS_ALUMNOS_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Notas de Prácticas:.
        /// </summary>
        internal static string FORMULARIO_NOTAS_EDIT_TITLE {
            get {
                return ResourceManager.GetString("FORMULARIO_NOTAS_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo horario:.
        /// </summary>
        internal static string HORARIO_ADD_TITLE {
            get {
                return ResourceManager.GetString("HORARIO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Horario:.
        /// </summary>
        internal static string HORARIO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("HORARIO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Horarios:.
        /// </summary>
        internal static string HORARIO_FIND_TITLE {
            get {
                return ResourceManager.GetString("HORARIO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios.
        /// </summary>
        internal static string HORARIOS {
            get {
                return ResourceManager.GetString("HORARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Imagen de Pregunta:.
        /// </summary>
        internal static string IMAGEN_PREGUNTA_VIEW_TITLE {
            get {
                return ResourceManager.GetString("IMAGEN_PREGUNTA_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Empleado:.
        /// </summary>
        internal static string INSTRUCTOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("INSTRUCTOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Empleado:.
        /// </summary>
        internal static string INSTRUCTOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("INSTRUCTOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Empleados:.
        /// </summary>
        internal static string INSTRUCTOR_FIND_TITLE {
            get {
                return ResourceManager.GetString("INSTRUCTOR_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string INSTRUCTORES {
            get {
                return ResourceManager.GetString("INSTRUCTORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Línea de Pedido.
        /// </summary>
        internal static string LINEAPEDIDO_ADD_TITLE {
            get {
                return ResourceManager.GetString("LINEAPEDIDO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detallar Línea de Pedido.
        /// </summary>
        internal static string LINEAPEDIDO_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("LINEAPEDIDO_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Línea de Pedido.
        /// </summary>
        internal static string LINEAPEDIDO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("LINEAPEDIDO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Material:.
        /// </summary>
        internal static string MATERIAL_ADD_TITLE {
            get {
                return ResourceManager.GetString("MATERIAL_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Material Docente:.
        /// </summary>
        internal static string MATERIAL_EDIT_TITLE {
            get {
                return ResourceManager.GetString("MATERIAL_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Materiales:.
        /// </summary>
        internal static string MATERIAL_FIND_TITLE {
            get {
                return ResourceManager.GetString("MATERIAL_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Docente.
        /// </summary>
        internal static string MATERIALES {
            get {
                return ResourceManager.GetString("MATERIALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Módulo:.
        /// </summary>
        internal static string MODULO_ADD_TITLE {
            get {
                return ResourceManager.GetString("MODULO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Módulo:.
        /// </summary>
        internal static string MODULO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("MODULO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Módulos:.
        /// </summary>
        internal static string MODULO_FIND_TITLE {
            get {
                return ResourceManager.GetString("MODULO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos.
        /// </summary>
        internal static string MODULOS {
            get {
                return ResourceManager.GetString("MODULOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipios:.
        /// </summary>
        internal static string MUNICIPIO_TITLE {
            get {
                return ResourceManager.GetString("MUNICIPIO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APTO.
        /// </summary>
        internal static string NO_APTO_LABEL {
            get {
                return ResourceManager.GetString("NO_APTO_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Nota de alumno:.
        /// </summary>
        internal static string NOTA_ALUMNO_TITLE {
            get {
                return ResourceManager.GetString("NOTA_ALUMNO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas de Alumnos.
        /// </summary>
        internal static string NOTAS_ALUMNOS {
            get {
                return ResourceManager.GetString("NOTAS_ALUMNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Orden de la Clase:.
        /// </summary>
        internal static string ORDENAR_CLASES_TITLE {
            get {
                return ResourceManager.GetString("ORDENAR_CLASES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Orden:.
        /// </summary>
        internal static string ORDENAR_PREGUNTAS_EXAMEN_TITLE {
            get {
                return ResourceManager.GetString("ORDENAR_PREGUNTAS_EXAMEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Parte de Asistencia:.
        /// </summary>
        internal static string P_ASISTENCIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("P_ASISTENCIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Parte de Asistencia:.
        /// </summary>
        internal static string P_ASISTENCIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("P_ASISTENCIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Partes de Asistencia:.
        /// </summary>
        internal static string P_ASISTENCIA_FIND_TITLE {
            get {
                return ResourceManager.GetString("P_ASISTENCIA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Plan de Estudios:.
        /// </summary>
        internal static string PLAN_DOCENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLAN_DOCENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Plan de Estudios:.
        /// </summary>
        internal static string PLAN_DOCENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLAN_DOCENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Planes de Estudios:.
        /// </summary>
        internal static string PLAN_DOCENTE_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLAN_DOCENTE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Plan Extra:.
        /// </summary>
        internal static string PLAN_EXTRA_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLAN_EXTRA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Plan Extra:.
        /// </summary>
        internal static string PLAN_EXTRA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLAN_EXTRA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Planes Extra:.
        /// </summary>
        internal static string PLAN_EXTRA_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLAN_EXTRA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Anuales:.
        /// </summary>
        internal static string PLANES_ANUALES {
            get {
                return ResourceManager.GetString("PLANES_ANUALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes de Estudios.
        /// </summary>
        internal static string PLANES_DOCENTES {
            get {
                return ResourceManager.GetString("PLANES_DOCENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Extra.
        /// </summary>
        internal static string PLANES_EXTRA {
            get {
                return ResourceManager.GetString("PLANES_EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas de Exámenes.
        /// </summary>
        internal static string PLANTILLA_EXAMEN {
            get {
                return ResourceManager.GetString("PLANTILLA_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Plantilla de Examen:.
        /// </summary>
        internal static string PLANTILLA_EXAMEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLANTILLA_EXAMEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Plantilla de Examen:.
        /// </summary>
        internal static string PLANTILLA_EXAMEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLANTILLA_EXAMEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Plantillas de Exámenes:.
        /// </summary>
        internal static string PLANTILLA_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLANTILLA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Prácticas:.
        /// </summary>
        internal static string PRACTICAS_TITLE {
            get {
                return ResourceManager.GetString("PRACTICAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Pregunta:.
        /// </summary>
        internal static string PREGUNTA_ADD_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Pregunta:.
        /// </summary>
        internal static string PREGUNTA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Preguntas:.
        /// </summary>
        internal static string PREGUNTA_FIND_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        internal static string PREGUNTAS {
            get {
                return ResourceManager.GetString("PREGUNTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Preguntas:.
        /// </summary>
        internal static string PREGUNTAS_PLANTILLA_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTAS_PLANTILLA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string PRINT_TITLE {
            get {
                return ResourceManager.GetString("PRINT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Promoción:.
        /// </summary>
        internal static string PROMOCION_ADD_TITLE {
            get {
                return ResourceManager.GetString("PROMOCION_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Promoción:.
        /// </summary>
        internal static string PROMOCION_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PROMOCION_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Promociones:.
        /// </summary>
        internal static string PROMOCION_FIND_TITLE {
            get {
                return ResourceManager.GetString("PROMOCION_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        internal static string PROMOCIONES {
            get {
                return ResourceManager.GetString("PROMOCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas:.
        /// </summary>
        internal static string RESPUESTAS_TITLE {
            get {
                return ResourceManager.GetString("RESPUESTAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen Examen.
        /// </summary>
        internal static string RESUMEN_EXAMEN_TITLE {
            get {
                return ResourceManager.GetString("RESUMEN_EXAMEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Revisión:.
        /// </summary>
        internal static string REVISION_ADD_TITLE {
            get {
                return ResourceManager.GetString("REVISION_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Revisión:.
        /// </summary>
        internal static string REVISION_EDIT_TITLE {
            get {
                return ResourceManager.GetString("REVISION_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisiones:.
        /// </summary>
        internal static string REVISION_TITLE {
            get {
                return ResourceManager.GetString("REVISION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar alumnos:.
        /// </summary>
        internal static string SELECT_ALUMNOS {
            get {
                return ResourceManager.GetString("SELECT_ALUMNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Plantilla de Examen.
        /// </summary>
        internal static string SELECT_PLANTILLA {
            get {
                return ResourceManager.GetString("SELECT_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Preguntas:.
        /// </summary>
        internal static string SELECT_PREGUNTAS {
            get {
                return ResourceManager.GetString("SELECT_PREGUNTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Servicio de Proveedor.
        /// </summary>
        internal static string SERVICIOPROVEEDOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Servicio de Proveedor:.
        /// </summary>
        internal static string SERVICIOPROVEEDOR_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN CALIFICAR.
        /// </summary>
        internal static string SIN_CALIFICAR_LABEL {
            get {
                return ResourceManager.GetString("SIN_CALIFICAR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Submódulo:.
        /// </summary>
        internal static string SUBMODULO_ADD_TITLE {
            get {
                return ResourceManager.GetString("SUBMODULO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Submódulo:.
        /// </summary>
        internal static string SUBMODULO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("SUBMODULO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Asignación de Submódulos por Instructor:.
        /// </summary>
        internal static string SUBMODULO_INSTRUCTOR_PROMOCION_VIEW_TITLE {
            get {
                return ResourceManager.GetString("SUBMODULO_INSTRUCTOR_PROMOCION_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas:.
        /// </summary>
        internal static string TEMA_TITLE {
            get {
                return ResourceManager.GetString("TEMA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Teóricas:.
        /// </summary>
        internal static string TEORICAS_TITLE {
            get {
                return ResourceManager.GetString("TEORICAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Preguntas:.
        /// </summary>
        internal static string VER_PREGUNTAS_TITLE {
            get {
                return ResourceManager.GetString("VER_PREGUNTAS_TITLE", resourceCulture);
            }
        }
    }
}
