//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Instruction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Instruction.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar el alumno porque tiene exámenes asociados..
        /// </summary>
        internal static string ALUMNO_CON_EXAMENES {
            get {
                return ResourceManager.GetString("ALUMNO_CON_EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar el alumno porque tiene partes de faltas asociados..
        /// </summary>
        internal static string ALUMNO_CON_PARTES_DE_FALTAS {
            get {
                return ResourceManager.GetString("ALUMNO_CON_PARTES_DE_FALTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar el alumno porque tiene prácticas asociadas..
        /// </summary>
        internal static string ALUMNO_CON_PRACTICAS {
            get {
                return ResourceManager.GetString("ALUMNO_CON_PRACTICAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este alumno ya está matriculado en esta convocatoria.
        /// </summary>
        internal static string ALUMNO_YA_MATRICULADO {
            get {
                return ResourceManager.GetString("ALUMNO_YA_MATRICULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si cancela se perderán los últimos cambios realizados.
        ///                               ¿Cancelar?.
        /// </summary>
        internal static string CANCEL_CONFIRM {
            get {
                return ResourceManager.GetString("CANCEL_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clase que está intentando borrar ya ha sigo asignada en algún horario..
        /// </summary>
        internal static string CLASE_ASIGNADA {
            get {
                return ResourceManager.GetString("CLASE_ASIGNADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La configuración introducida para los horarios de la promoción no es coherente.
        ///Por favor, revise antes de guardar..
        /// </summary>
        internal static string CONFIGURACION_NO_VALIDA {
            get {
                return ResourceManager.GetString("CONFIGURACION_NO_VALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha finalizado el plazo de admisión de matrículas para esta convocatoria. Si desea realizar una matrícula modifique el plazo de admisión..
        /// </summary>
        internal static string CONVOCATORIA_FINALIZADA {
            get {
                return ResourceManager.GetString("CONVOCATORIA_FINALIZADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando horario....
        /// </summary>
        internal static string CREANDO_HORARIO {
            get {
                return ResourceManager.GetString("CREANDO_HORARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando partes de asistencia....
        /// </summary>
        internal static string CREANDO_PARTES_ASISTENCIA {
            get {
                return ResourceManager.GetString("CREANDO_PARTES_ASISTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cronograma se ha generado satisfactoriamente. .
        /// </summary>
        internal static string CRONOGRAMA_GENERADO_CON_EXITO {
            get {
                return ResourceManager.GetString("CRONOGRAMA_GENERADO_CON_EXITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un elemento de esta entidad que está siendo editado. Para editar otro, por favor, cierre el anterior..
        /// </summary>
        internal static string CURRENT_EDITION {
            get {
                return ResourceManager.GetString("CURRENT_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay elementos en edición ¿Está seguro de que desea cerrar?.
        /// </summary>
        internal static string CURRENT_EDITION_CLOSE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el elemento. Está siendo editado.
        /// </summary>
        internal static string CURRENT_EDITION_DELETE {
            get {
                return ResourceManager.GetString("CURRENT_EDITION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Confirmar la eliminación del elemento seleccionado?.
        /// </summary>
        internal static string DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El borrado total de una empresa puede tardar algunos minutos.
        ///      ¿Confirmar la eliminación de la empresa seleccionada?.
        /// </summary>
        internal static string DELETE_CONFIRM_EMPRESA {
            get {
                return ResourceManager.GetString("DELETE_CONFIRM_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descargando actualización....
        /// </summary>
        internal static string DOWNLOADING_DATA {
            get {
                return ResourceManager.GetString("DOWNLOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia de seguridad generada con éxito.
        /// </summary>
        internal static string DUMP_OK {
            get {
                return ResourceManager.GetString("DUMP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando copia de seguridad....
        /// </summary>
        internal static string DUMPING_BACKUP {
            get {
                return ResourceManager.GetString("DUMPING_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe otro elemento con ese códígo..
        /// </summary>
        internal static string DUPLICATED_CODE {
            get {
                return ResourceManager.GetString("DUPLICATED_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede borrar la empresa activa..
        /// </summary>
        internal static string EMPRESA_NEEDED {
            get {
                return ResourceManager.GetString("EMPRESA_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe vacío.
        /// </summary>
        internal static string EMPTY_REPORT {
            get {
                return ResourceManager.GetString("EMPTY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string ENTERPRISE_MAX_LIMITED {
            get {
                return ResourceManager.GetString("ENTERPRISE_MAX_LIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de empresas de la aplicación ha alcanzado el límite permitido..
        /// </summary>
        internal static string ENTERPRISE_MAX_LIMITED_NOTICE {
            get {
                return ResourceManager.GetString("ENTERPRISE_MAX_LIMITED_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para acceder a esta empresa.
        /// </summary>
        internal static string ENTERPRISE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ENTERPRISE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario que está intentando modificar no ha podido generar los partes de faltas..
        /// </summary>
        internal static string ERROR_CREAR_PARTES {
            get {
                return ResourceManager.GetString("ERROR_CREAR_PARTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha habido algún error al generar el albarán de instructor. Compruebe que el albarán asociado no haya sido facturado y que los albaranes de instructor tengan serie y producto por defecto asociados..
        /// </summary>
        internal static string ERROR_GENERACION_ALBARAN_INSTRUCTOR {
            get {
                return ResourceManager.GetString("ERROR_GENERACION_ALBARAN_INSTRUCTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han podido duplicar todas las preguntas del examen seleccionado ya que al menos una de ellas no está disponible en la fecha en la que va a tener lugar el examen..
        /// </summary>
        internal static string EXAMEN_DUPLICADO_CON_PREGUNTAS_NO_DISPONIBLES {
            get {
                return ResourceManager.GetString("EXAMEN_DUPLICADO_CON_PREGUNTAS_NO_DISPONIBLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede llevar a cabo la acción seleccionada si el examen aún no ha sido emitido.
        /// </summary>
        internal static string EXAMEN_NO_EMITIDO {
            get {
                return ResourceManager.GetString("EXAMEN_NO_EMITIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para acceder a las preguntas debe primero cerrar la ventana de edición de exámenes..
        /// </summary>
        internal static string EXAMENES_MNG_OPEN {
            get {
                return ResourceManager.GetString("EXAMENES_MNG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando cronograma....
        /// </summary>
        internal static string GENERANDO_CRONOGRAMA {
            get {
                return ResourceManager.GetString("GENERANDO_CRONOGRAMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generando sesiones del horario....
        /// </summary>
        internal static string GENERANDO_SESIONES {
            get {
                return ResourceManager.GetString("GENERANDO_SESIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de imprimir el examen actual se debe guardar. ¿Desea guardar ahora e imprimir el examen?.
        /// </summary>
        internal static string GUARDADO_EXAMEN {
            get {
                return ResourceManager.GetString("GUARDADO_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario que está intentando borrar contiene clases que han sido confirmadas y no puede ser borrado..
        /// </summary>
        internal static string HORARIO_CONFIRMADO {
            get {
                return ResourceManager.GetString("HORARIO_CONFIRMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un horario generado para la promoción y fecha seleccionadas..
        /// </summary>
        internal static string HORARIO_EXISTENTE {
            get {
                return ResourceManager.GetString("HORARIO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha generado ningún horario.
        /// </summary>
        internal static string HORARIO_NO_GENERADO {
            get {
                return ResourceManager.GetString("HORARIO_NO_GENERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el informe de ampliación {0}..
        /// </summary>
        internal static string INFORME_AMPLIACION_MODIFICADO {
            get {
                return ResourceManager.GetString("INFORME_AMPLIACION_MODIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el informe de correcciones {0}..
        /// </summary>
        internal static string INFORME_CORRECCIONES_MODIFICADO {
            get {
                return ResourceManager.GetString("INFORME_CORRECCIONES_MODIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha modificado el informe de discrepancia {0}..
        /// </summary>
        internal static string INFORME_DISCREPANCIA_MODIFICADO {
            get {
                return ResourceManager.GetString("INFORME_DISCREPANCIA_MODIFICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo &quot;{0}&quot; contiene datos no válidos..
        /// </summary>
        internal static string INVALID_FIELD_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FIELD_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo modificado contiene datos no válidos..
        /// </summary>
        internal static string INVALID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando datos....
        /// </summary>
        internal static string LOADING_DATA {
            get {
                return ResourceManager.GetString("LOADING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible bloquear el elemento seleccionado.
        ///Otro usuario está modificándolo en este momento. .
        /// </summary>
        internal static string LOCK_ERROR {
            get {
                return ResourceManager.GetString("LOCK_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error autentificando al usuario. Revise nombre de usuario y contraseña..
        /// </summary>
        internal static string LOGIN_ERROR {
            get {
                return ResourceManager.GetString("LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificando la clase actual....
        /// </summary>
        internal static string MODIFICANDO_CLASE {
            get {
                return ResourceManager.GetString("MODIFICANDO_CLASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este alumno no está asociado a ningún cliente. Es necesario asociar un cliente antes de  tramitar la matrícula.
        /// </summary>
        internal static string NO_CLIENT_ASSOCIATED {
            get {
                return ResourceManager.GetString("NO_CLIENT_ASSOCIATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha seleccionado ningun cliente..
        /// </summary>
        internal static string NO_CLIENT_SELECTED {
            get {
                return ResourceManager.GetString("NO_CLIENT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos disponibles para realizar una selección específica para este tipo de informe..
        /// </summary>
        internal static string NO_DATA_ENTITY {
            get {
                return ResourceManager.GetString("NO_DATA_ENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existen datos para imprimir..
        /// </summary>
        internal static string NO_DATA_REPORTS {
            get {
                return ResourceManager.GetString("NO_DATA_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario actual no puede ser eliminado.
        /// </summary>
        internal static string NO_DELETE_USER {
            get {
                return ResourceManager.GetString("NO_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han encontrado elementos coincidentes.
        /// </summary>
        internal static string NO_RESULTS {
            get {
                return ResourceManager.GetString("NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un elemento de la lista.
        /// </summary>
        internal static string NO_SELECTED {
            get {
                return ResourceManager.GetString("NO_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No es posible realizar la acción solicitada ({0}) sobre una auditoría en estado {1}..
        /// </summary>
        internal static string NOT_ENABLED_ACTION {
            get {
                return ResourceManager.GetString("NOT_ENABLED_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede modificar el campo {0} de una auditoría en estado {1}..
        /// </summary>
        internal static string NOT_ENABLED_PROPERTY {
            get {
                return ResourceManager.GetString("NOT_ENABLED_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas introducidas no son iguales.
        /// </summary>
        internal static string NOT_EQUAL_PASS {
            get {
                return ResourceManager.GetString("NOT_EQUAL_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha sido posible realizar la operación.
        ///.
        /// </summary>
        internal static string OPERATION_ERROR {
            get {
                return ResourceManager.GetString("OPERATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parte de faltas que intenta borrar ha sido confirmado y tiene conceptos de albarán asociados. Debe ir a Facturación y eliminar los conceptos asociados antes de borrar..
        /// </summary>
        internal static string PARTE_CON_CONCEPTOS_ASOCIADOS {
            get {
                return ResourceManager.GetString("PARTE_CON_CONCEPTOS_ASOCIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha escrito una contraseña. ¿Está seguro de que desea que el usuario no posea contraseña?.
        /// </summary>
        internal static string PASSWORD_NULL {
            get {
                return ResourceManager.GetString("PASSWORD_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pregunta número {0} ha sido reservada por otro usuario. 
        ///Para poder guardar el examen debe eliminarla del mismo..
        /// </summary>
        internal static string PREGUNTA_INCLUIDA {
            get {
                return ResourceManager.GetString("PREGUNTA_INCLUIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La pregunta actual está incluída en algún examen que aún no ha sido emitido. 
        ///No será posible marcarla como inactiva hasta que no deje de estar reservada..
        /// </summary>
        internal static string PREGUNTA_RESERVADA {
            get {
                return ResourceManager.GetString("PREGUNTA_RESERVADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las siguientes preguntas están inactivas y no podrán aparecer en el examen: {0}.
        ///Actívelas si desea que aparezcan en el mismo..
        /// </summary>
        internal static string PREGUNTAS_INACTIVAS {
            get {
                return ResourceManager.GetString("PREGUNTAS_INACTIVAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para acceder a los exámenes debe primero cerrar la ventana de edición de preguntas..
        /// </summary>
        internal static string PREGUNTAS_MNG_OPEN {
            get {
                return ResourceManager.GetString("PREGUNTAS_MNG_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no autorizado para llevar a cabo la acción seleccionada..
        /// </summary>
        internal static string RESTORE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("RESTORE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando....
        /// </summary>
        internal static string SAVING {
            get {
                return ResourceManager.GetString("SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede guardar el horario, existen sesiones que no tienen instructor asignado..
        /// </summary>
        internal static string SESION_SIN_PROFESOR {
            get {
                return ResourceManager.GetString("SESION_SIN_PROFESOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + = Agregar.
        /// </summary>
        internal static string STATUS_GENERICO {
            get {
                return ResourceManager.GetString("STATUS_GENERICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los submódulos deben tener asociados al menos un tema.
        /// </summary>
        internal static string SUBMODULO_SIN_TEMAS {
            get {
                return ResourceManager.GetString("SUBMODULO_SIN_TEMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tema que está intentando eliminar tiene preguntas asociadas y no podrá ser eliminado..
        /// </summary>
        internal static string TEMA_CON_PREGUNTAS {
            get {
                return ResourceManager.GetString("TEMA_CON_PREGUNTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las preguntas del tema se han duplicado correctamente.
        /// </summary>
        internal static string TEMA_DUPLICADO_OK {
            get {
                return ResourceManager.GetString("TEMA_DUPLICADO_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando disponibilidad de los instructores....
        /// </summary>
        internal static string UPDATING_INSTRUCTORES_HORARIO {
            get {
                return ResourceManager.GetString("UPDATING_INSTRUCTORES_HORARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando instructores, disponibildades y clases sin programar....
        /// </summary>
        internal static string UPDATING_PROMOCION_HORARIO {
            get {
                return ResourceManager.GetString("UPDATING_PROMOCION_HORARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobando permisos....
        /// </summary>
        internal static string VALIDATION_MSG {
            get {
                return ResourceManager.GetString("VALIDATION_MSG", resourceCulture);
            }
        }
    }
}
