//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Instruction.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Instruction.Resources.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to borrar_16.png.
        /// </summary>
        internal static string ELIMINAR_BT_IMG {
            get {
                return ResourceManager.GetString("ELIMINAR_BT_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulos.ico.
        /// </summary>
        internal static string MODULO_ICO {
            get {
                return ResourceManager.GetString("MODULO_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel.ico.
        /// </summary>
        internal static string NIVEL_ICO {
            get {
                return ResourceManager.GetString("NIVEL_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ordenar_16.png.
        /// </summary>
        internal static string ORDENAR_BT_IMG {
            get {
                return ResourceManager.GetString("ORDENAR_BT_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueada.ico.
        /// </summary>
        internal static string PREGUNTA_BLOQUEADA_ICO {
            get {
                return ResourceManager.GetString("PREGUNTA_BLOQUEADA_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible.ico.
        /// </summary>
        internal static string PREGUNTA_DISPONIBLE_ICO {
            get {
                return ResourceManager.GetString("PREGUNTA_DISPONIBLE_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservada.ico.
        /// </summary>
        internal static string PREGUNTA_RESERVADA_ICO {
            get {
                return ResourceManager.GetString("PREGUNTA_RESERVADA_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submodulos.ico.
        /// </summary>
        internal static string SUBMODULOS_ICO {
            get {
                return ResourceManager.GetString("SUBMODULOS_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submodulos_verde.ico.
        /// </summary>
        internal static string SUBMODULOS_LIBRE_ICO {
            get {
                return ResourceManager.GetString("SUBMODULOS_LIBRE_ICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver_16.png.
        /// </summary>
        internal static string VER_BT_IMG {
            get {
                return ResourceManager.GetString("VER_BT_IMG", resourceCulture);
            }
        }
    }
}
